# Generated by Django 2.1.2 on 2018-10-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.DecimalField(decimal_places=0, max_digits=4)),
                ('primary_contact_name', models.CharField(max_length=25)),
                ('primary_contact_position', models.CharField(max_length=25)),
                ('primary_contact_department', models.CharField(max_length=15)),
                ('primary_contact_phone', models.CharField(max_length=17)),
                ('primary_contact_email', models.CharField(max_length=30)),
            ],
        ),
    ]
