# Generated by Django 2.1.2 on 2018-10-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20181028_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='primary_contact_name',
            field=models.CharField(max_length=24),
        ),
    ]
