# Generated by Django 2.1.2 on 2018-10-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20181028_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
